Kick off the dev path for back-end patterns
Selleo/DevPath pull request #109
Opened 2021-05-14 17:11 UTC by simon2k

2021-05-21 09:27 UTC, PoslinskiNet commented
@kayinrage @mikoscz @stevo @qbart  feel free to provide feedback and your perspective [as TLs and/or Mastery seekers, Tech Evangelists, Tech Experts within Selleo around backend technologies/programming in general]

2021-06-23 15:32 UTC, qbart requested changes
I've left some comments, for the first iteration it's pretty good - it would great to receive feedback from people.

2021-06-23 15:32 UTC, qbart commented on content/web_development/skills/Backend Patterns/advanced.md
> +- Name, explain, choose and apply a wide range of software design patterns to solve particular problems
```suggestion
- Name, explain, choose and apply a wide range of software design patterns to solve problems
```

2021-06-23 15:32 UTC, qbart commented on content/web_development/skills/Backend Patterns/basics.md
> +- Demonstrate strong skills in TDD/BDD
```suggestion
- Demonstrate good skills in TDD/BDD
```

2021-06-23 15:32 UTC, qbart commented on content/web_development/skills/Backend Patterns/advanced.md
> +- What is Sanitization? When can it be useful?
Sanitazation could be a part of basics

2021-06-23 15:32 UTC, qbart commented on content/web_development/skills/Backend Patterns/basics.md
> +    - [Thoughtbot - DIP](https://thoughtbot.com/upcase/videos/dependency-inversion-principle) (OPTIONAL)
How about moving few of these to advanced?

2021-06-23 20:29 UTC, simon2k commented on content/web_development/skills/Backend Patterns/basics.md
> +- What are callbacks in Ruby on Rails?
Thanks @qbart for the first review! I would like to make this framework/language independent (if it is possible). What do you think of it? FYI, this is a copy'n'paste extraction from our Rails dev path.

2021-06-24 10:02 UTC, qbart commented on content/web_development/skills/Backend Patterns/basics.md
> +- What are callbacks in Ruby on Rails?
That was my initial assumption to make it technology agnostic but I've seen so many rails specific stuff that I thought it's for rails :smile: I'll go through this again and leave suggestions for making it that way

2021-12-01 13:49 UTC, PoslinskiNet commented
@simon2k @qbart what is the status of this one?

2021-12-21 13:29 UTC, PoslinskiNet commented
@simon2k @qbart any thoughts on this one?

2022-02-28 08:38 UTC, Skysplit commented
bump

2022-03-24 13:10 UTC, PoslinskiNet commented
@simon2k @qbart any thoughts on this one? This is my last call. I will close it automatically after a month from now if no response, since don't see any movement in this area.

2022-03-24 14:39 UTC, qbart commented
I think we are lost here, I would close it for now and then create new one that is technology agnostic.

2022-03-24 14:45 UTC, simon2k commented
It's gonna be re-created.

2022-03-24 14:45 UTC, closed without merging