[DRAFT]docs: update react native basics path
Selleo/DevPath pull request #212
Opened 2022-12-30 15:18 UTC by bartoszboruta

2023-01-02 11:31 UTC, k1eu requested changes

2023-01-02 11:31 UTC, k1eu commented on content/web_development/skills/Framework and language/react-native/basics.md
> +React Native doesn't have a built-in idea of a global history stack like a web browser does -- this is where React Navigation enters the story.
```suggestion
React Native doesn't have a built-in idea of a global history stack like a web browser does - this is where React Navigation comes into play.
```

2023-01-02 11:31 UTC, k1eu commented on content/web_development/skills/Framework and language/react-native/basics.md
> +React Native doesn't have a built-in idea of a global history stack like a web browser does -- this is where React Navigation enters the story.
```suggestion
React Native doesn't have a built-in idea of a global history stack like a web browser does - this is where React Navigation enters the chat.
```

2023-01-02 11:31 UTC, k1eu commented on content/web_development/skills/Framework and language/react-native/basics.md
> +React Native doesn't have a built-in idea of a global history stack like a web browser does -- this is where React Navigation enters the story.
sounds better and I think is more appropriate :D

2023-01-02 11:31 UTC, k1eu commented on content/web_development/skills/Framework and language/react-native/basics.md
> +- Simple data fetch/update requests
```suggestion
- Add simple data fetching requesting and updating mutations
```

2023-01-02 11:31 UTC, k1eu commented on content/web_development/skills/Framework and language/react-native/basics.md
> +I need to know that you are able to style components, by using original ReactNative StyleSheets or StyledComponents
Do we want to propose StyledComponents as a desired styling technology?

2023-01-02 11:31 UTC, k1eu commented on content/web_development/skills/Framework and language/react-native/basics.md
> +- Where is an information about errors and touched inputs when using Formik?
or react Hook Form? maybe they can choose here their prefered library

2023-01-02 11:31 UTC, k1eu commented on content/web_development/skills/Framework and language/react-native/basics.md
> +
Maybe zod can be also added here?

2023-01-02 11:31 UTC, k1eu commented on content/web_development/skills/Framework and language/react-native/basics.md
> +  - 📗 [Yup - form validation](https://github.com/jquense/yup)
```suggestion
  - 📗 [Yup - form validation](https://github.com/jquense/yup)
  - 📗 [Zod - form validation](https://zod.dev/)  
```

2023-01-02 11:31 UTC, k1eu commented on content/web_development/skills/Framework and language/react-native/basics.md
> +- What is a library we use to validation in formik? How to write own validation function?
What do you think about adding a question about a diff between those libraries, their rerenders patters, how to avoid unnecesary etc.

2023-01-02 11:31 UTC, k1eu commented on content/web_development/skills/Framework and language/react-native/basics.md
> +  - apply some styles
```suggestion
  - Apply some basic styles
```

2023-01-02 11:31 UTC, k1eu commented on content/web_development/skills/Framework and language/react-native/basics.md
> +  - make sure it will be testable
```suggestion
  - Make sure it is testable
```

2023-01-02 11:31 UTC, k1eu commented on content/web_development/skills/Framework and language/react-native/basics.md
> +  - it should be used by external library
```suggestion
  - It should be used by external library
```

2023-01-02 11:31 UTC, k1eu commented on content/web_development/skills/Framework and language/react-native/basics.md
> +- Create form for create and edit todos and habits
```suggestion
- Create form for creating and editing todos and habits
```

2023-01-02 11:31 UTC, k1eu commented on content/web_development/skills/Framework and language/react-native/basics.md
> +  - you should not be able to add a form with a name that does not exist in form type
```suggestion
  - You should not be able to add a form with a name that does not exist in form type
```

2023-01-02 11:31 UTC, k1eu commented on content/web_development/skills/Framework and language/react-native/basics.md
> +  - handle submit should be type safe
```suggestion
  - Handle submit should be type safe
```

2023-01-02 11:31 UTC, k1eu commented on content/web_development/skills/Framework and language/react-native/basics.md
Maybe let's add a point that says - that usage of a state mgmt library should be implemented in a typesafe way

2023-01-02 11:33 UTC, k1eu commented on content/web_development/skills/Framework and language/react-native/basics.md
> +I need to know that you are able to style components, by using original ReactNative StyleSheets or StyledComponents
Also `I need to know tha you're able to...` maybe we should do it less personally sounding?

2023-01-04 10:35 UTC, Darex1991 approved these changes
👍

2023-01-04 10:35 UTC, Darex1991 commented on content/web_development/skills/Framework and language/react-native/basics.md
> +Know how to manage the app state.
you can add some information, like https://blog.logrocket.com/comparing-react-native-state-management-libraries/

2023-01-10 13:07 UTC, qbart approved these changes

2023-01-17 08:59 UTC, michalfirszt approved these changes

2023-01-27 12:06 UTC, k1eu approved these changes

2023-01-27 12:21 UTC, merged