WIP: The *new* NodeJS dev path
Selleo/DevPath pull request #89
Opened 2021-02-25 22:37 UTC by simon2k

2021-02-25 22:59 UTC, PoslinskiNet commented on content/web_development/skills/Framework and language/nodejs/basics.md
> +- [Ruby Monk - primer](https://rubymonk.com/learning/books/1-ruby-primer)
Ruby :) ?

2021-02-25 23:15 UTC, simon2k commented on content/web_development/skills/Framework and language/nodejs/basics.md
> +- [Ruby Monk - primer](https://rubymonk.com/learning/books/1-ruby-primer)
That is the evil of an early push to remote... *wip*

2021-02-26 05:43 UTC, PoslinskiNet commented on content/web_development/skills/Framework and language/nodejs/basics.md
> +- [Ruby Monk - primer](https://rubymonk.com/learning/books/1-ruby-primer)
From this point, it is mainly ruby. My question is, do you want to achieve similar results with NodeJS via building RoR like structure but in JS?

2021-02-26 09:05 UTC, simon2k commented on content/web_development/skills/Framework and language/nodejs/basics.md
> +- [Ruby Monk - primer](https://rubymonk.com/learning/books/1-ruby-primer)
The next parts are about Ruby since the proposed document is based on the one created for Ruby. I plan to adjust these parts to reflect the current state. The document can be quite similar to Ruby as Irek did a great job of describing the back-end and I think it is a good starting point. As I move forward with describing the JavaScript part I will steadily replace Ruby with JavaScript.

2021-04-08 07:03 UTC, PoslinskiNet commented
@simon2k what is the plan with this one?

2021-05-17 09:02 UTC, PoslinskiNet commented on content/web_development/skills/Framework and language/nestjs/basics.md
> +- REST API
@simon2k I can see the outline, but there is no particular reference to the outline in the content area.

Consider for greater standardization, a similar approach as we have in other frameworks:
- https://selleo.com/devpath/web_development/skills/framework-and-language/react/basics/
- https://selleo.com/devpath/web_development/skills/framework-and-language/elixir/basics/
- https://selleo.com/devpath/web_development/skills/framework-and-language/ruby_on_rails/basics/
- https://selleo.com/devpath/web_development/skills/framework-and-language/ember/basics/

So people can approach it with a step-by-step approach, understand one concept, then move to another. It will also make it more attractive for people who will pick it as their next framework of choice that way [not so scary, that they will have to dig too deep].

2021-05-17 09:05 UTC, PoslinskiNet commented on content/web_development/skills/Framework and language/nestjs/content_bank.md
> +### PDF Generation
Would be nice to make some distinction which one is obligatory [very hard to live without it and which one is optional]

📗 - Obligatory, 📙 - Optional (https://selleo.com/devpath/web_development/)

2021-05-17 09:07 UTC, PoslinskiNet commented on content/web_development/skills/Framework and language/nestjs/basics.md
> +- OpenAPI Specification
What will be there? I think it is already in API Expertise: https://selleo.com/devpath/web_development/skills/api_expertise/#-documentation

2021-05-17 09:10 UTC, PoslinskiNet commented on content/web_development/skills/Framework and language/javascript/basics.md
> +## Language's Basics
@pokiujf @tobob @simon2k @rxbsxn Maybe this should be a part of React/Ember/ReactNative as a prerequisite?

2021-05-17 09:15 UTC, PoslinskiNet commented on content/web_development/skills/Framework and language/typescript/basics.md
> +{{% /bubble%}}
Would be nice to have an outline, so we will know which features out of the language [that are not present in the javascript] we should focus on - so for instance, someone who already knows TypeScript, a bit will know should he learn something that will be critical or he already knows everything that we will need usually - otherwise, I've got an impression that someone should know every single feature of the language which is cool on some master level, but maybe not necessarily we need everything here? @simon2k

2021-05-17 09:16 UTC, PoslinskiNet requested changes
@simon2k I've left some feedback.

2021-05-24 06:40 UTC, PoslinskiNet commented on content/web_development/skills/Framework and language/nestjs/basics.md
> +- List and briefly describe a couple of built in pipes. ([answer](https://docs.nestjs.com/pipes))
```suggestion
- List and briefly describe a couple of built-in pipes. ([answer](https://docs.nestjs.com/pipes))
```

2021-05-24 06:47 UTC, simon2k commented on content/web_development/skills/Framework and language/nestjs/basics.md
> +- List and briefly describe a couple of built in pipes. ([answer](https://docs.nestjs.com/pipes))
:+1: Applied, squashed, and pushed

2021-05-25 11:14 UTC, PoslinskiNet approved these changes

2021-05-25 11:15 UTC, merged