Create Backbone for the Planning Bubble
Selleo/DevPath pull request #99
Opened 2021-04-05 08:03 UTC by Drakeoon

### Tasks:
- [ ] Create overview of the planning bubble
- [ ] Gather feedback on the proposed approach
- [ ] List powerful and useful questions both for your teammates and clients
- [ ] Write down an idea for Role Play Katas during the interview

2021-05-21 09:33 UTC, PoslinskiNet commented on content/web_development/skills/planning.md
> +- Assigning the Tasks
Delegation strategy

2021-05-21 09:33 UTC, PoslinskiNet commented on content/web_development/skills/planning.md
> +- Estimating Work
Estimate effort

2021-05-21 09:34 UTC, PoslinskiNet commented on content/web_development/skills/planning.md
> +- Backlog Prioritization
Not sure that backlog prioritization should lay above preparing tasks.

2021-05-21 09:35 UTC, PoslinskiNet commented on content/web_development/skills/planning.md
> +- Preparing Tasks
Divide feature / milestone / work etc. [try to focus more on why you are doing it instead of what you are doing].

2021-05-21 09:35 UTC, PoslinskiNet commented on content/web_development/skills/planning.md
> +- Preparing Stories
Eventually, we will have it on BA level I guess, am I right @maciejhubert?

2021-05-21 09:36 UTC, PoslinskiNet commented on content/web_development/skills/planning.md
> +- Preparing Stories
Maybe we should also consider here some testing strategies with QA?

2021-05-21 09:38 UTC, PoslinskiNet commented on content/web_development/skills/planning.md
> +- Reacting to Changes
Strategy for resolving blockers - pair programming, overcommunication, follow-ups with the team, dailies, matching timeline - especially monitor critical tasks [set priorities, sequential tasks that block others etc.]

2021-05-21 09:38 UTC, PoslinskiNet requested changes
@Drakeoon I've left some initial feedback.

2021-05-21 09:49 UTC, maciejhubert commented on content/web_development/skills/planning.md
> +- Preparing Stories
@PoslinskiNet it depends how extensive this bubble will be (I mean how much other content will be included). If no to much, then I would include it because of two reasons:
* it will take a lot of time to spread the BA around most of the projects in Selleo
* in case a project will not have a BA, the leader of the project should know the basis of creating Epics/Stories/Acceptance criteria

In case there is too much other content in planning bubble, we could consider including it somewhere else.

2021-05-21 09:51 UTC, maciejhubert commented on content/web_development/skills/planning.md
> +- Preparing Stories
@PoslinskiNet including testing strategies sounds great

2021-06-11 04:33 UTC, PoslinskiNet commented
@Drakeoon any updates on this one?

2021-06-14 06:29 UTC, Drakeoon commented on content/web_development/skills/planning.md
> +- Preparing Tasks
I don't think I understand your point, could you clarify what you meant?

2021-06-14 06:32 UTC, Drakeoon commented on content/web_development/skills/planning.md
> +- Preparing Stories
Many of the chapters from here can be covered by multiple roles in organization - I rely on my project experience. If you have a PM, PO and BA and you work as an augmented team, many chapters don't apply to you, because you don't hold responsibilities to maintain backlog, whereas on new, smaller clients you sometimes need to do that

2021-06-14 06:44 UTC, Drakeoon commented on content/web_development/skills/planning.md
> +- Reacting to Changes
Is this something you would like me to add to the path or change the existing ones? Also make sure the points above are somehow related to the "Planning bubble", as I don't want to overstuff this bubble with too many process-related topics, but let me know

2021-06-14 06:45 UTC, Drakeoon commented on content/web_development/skills/planning.md
> +- Backlog Prioritization
You can't prioritize backlog if you don't have epics/stories in it 😄

2021-06-14 06:49 UTC, Drakeoon commented
@PoslinskiNet I added some new chapters, as well as implemented some of your feedback notes. For the future feedback sessions, could you clarify whether I should add something or update existing entries? I sometimes couldn't understand what I should do :smile: Thanks!

2021-06-14 07:02 UTC, PoslinskiNet commented on content/web_development/skills/planning.md
> +- Preparing Tasks
I meant, that preparing tasks is more about outcome - what you are doing instead of why you are doing this - the goal is to Divide feature [somehow] - [start with why](https://www.ted.com/talks/simon_sinek_how_great_leaders_inspire_action?language=en)

2021-06-14 07:03 UTC, PoslinskiNet commented on content/web_development/skills/planning.md
> +- Reacting to Changes
Leave it as it is for now - let's finish it in the slimmest possible form.

2021-06-14 07:04 UTC, PoslinskiNet commented on content/web_development/skills/planning.md
> +- Backlog Prioritization
It depends on how you understand "preparing tasks" - define them or update them with a more detailed description.

2021-06-14 07:07 UTC, PoslinskiNet commented on content/web_development/skills/planning.md
> +- Preparing Stories
Keep it as it is for now - we can extend it later if needed.

2021-06-14 07:10 UTC, PoslinskiNet commented
@Drakeoon sure, I will try to clarify next time in more details what is the reason for the change request. I've replied in places that were unclear.

2021-06-14 07:12 UTC, Drakeoon commented on content/web_development/skills/planning.md
> +- Preparing Tasks
I think it makes sense now, I will apply your suggestion 👍🏻

2021-06-14 15:17 UTC, Drakeoon commented on content/web_development/skills/planning.md
> +- Preparing Tasks
I've just gone through the code a little bit and found that I do present the `why` behind preparing tasks and prioritizing product backlog (see screenshot below)
![image](https://user-images.githubusercontent.com/24693481/121916051-163caa00-cd34-11eb-8f0a-514df083d594.png)

I don't think changing the area title to "Divide Story" gives more value that "Preparing Tasks" - if you have a better idea that would illustrate the process better and give more meaning to it, I'll replace it. I want to avoid having sections like:
1. Dividing feature scope into smaller chunks (epics)
2. Dividing epics into smaller chunks (stories)
3. Dividing stories into smaller chunks (tasks)

2021-06-14 15:21 UTC, Drakeoon commented on content/web_development/skills/planning.md
> +- Backlog Prioritization
I've enhanced the Planning area description, can also provide more descriptions for each step (which was uncommon in other bubbles), but there's a lot theory here, so maybe it makes sense. Take a look here: 3deca63

2021-06-15 05:45 UTC, PoslinskiNet commented on content/web_development/skills/planning.md
> +- Preparing Tasks
![Good](https://pbs.twimg.com/media/EdivxqBXYAE2sSH.jpg)

2021-06-25 19:38 UTC, Drakeoon commented
@PoslinskiNet Please take a look at my recent changes, I think we've arrived at a place where we can ship it. There are some things missing like katas, but AFAIK they won't be needed soon (company strategy) so maybe let's leave them for when they're needed. What do you think?

2021-06-26 07:33 UTC, PoslinskiNet commented on content/web_development/skills/planning.md
> +- What is an eample of Estimated vs. True team's Velocity?
```suggestion
- What is an example of Estimated vs. True team's Velocity?
```

2021-06-26 07:34 UTC, PoslinskiNet approved these changes
Great job! I've found one typo.

2021-06-28 05:20 UTC, merged